require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProcessFlowsController do

  def mock_process_flow(stubs={})
    @mock_process_flow ||= mock_model(ProcessFlow, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all process_flows as @process_flows" do
      ProcessFlow.stub(:all) { [mock_process_flow] }
      get :index
      assigns(:process_flows).should eq([mock_process_flow])
    end
  end

  describe "GET show" do
    it "assigns the requested process_flow as @process_flow" do
      ProcessFlow.stub(:find).with("37") { mock_process_flow }
      get :show, :id => "37"
      assigns(:process_flow).should be(mock_process_flow)
    end
  end

  describe "GET new" do
    it "assigns a new process_flow as @process_flow" do
      ProcessFlow.stub(:new) { mock_process_flow }
      get :new
      assigns(:process_flow).should be(mock_process_flow)
    end
  end

  describe "GET edit" do
    it "assigns the requested process_flow as @process_flow" do
      ProcessFlow.stub(:find).with("37") { mock_process_flow }
      get :edit, :id => "37"
      assigns(:process_flow).should be(mock_process_flow)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created process_flow as @process_flow" do
        ProcessFlow.stub(:new).with({'these' => 'params'}) { mock_process_flow(:save => true) }
        post :create, :process_flow => {'these' => 'params'}
        assigns(:process_flow).should be(mock_process_flow)
      end

      it "redirects to the created process_flow" do
        ProcessFlow.stub(:new) { mock_process_flow(:save => true) }
        post :create, :process_flow => {}
        response.should redirect_to(process_flow_url(mock_process_flow))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved process_flow as @process_flow" do
        ProcessFlow.stub(:new).with({'these' => 'params'}) { mock_process_flow(:save => false) }
        post :create, :process_flow => {'these' => 'params'}
        assigns(:process_flow).should be(mock_process_flow)
      end

      it "re-renders the 'new' template" do
        ProcessFlow.stub(:new) { mock_process_flow(:save => false) }
        post :create, :process_flow => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested process_flow" do
        ProcessFlow.stub(:find).with("37") { mock_process_flow }
        mock_process_flow.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :process_flow => {'these' => 'params'}
      end

      it "assigns the requested process_flow as @process_flow" do
        ProcessFlow.stub(:find) { mock_process_flow(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:process_flow).should be(mock_process_flow)
      end

      it "redirects to the process_flow" do
        ProcessFlow.stub(:find) { mock_process_flow(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(process_flow_url(mock_process_flow))
      end
    end

    describe "with invalid params" do
      it "assigns the process_flow as @process_flow" do
        ProcessFlow.stub(:find) { mock_process_flow(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:process_flow).should be(mock_process_flow)
      end

      it "re-renders the 'edit' template" do
        ProcessFlow.stub(:find) { mock_process_flow(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested process_flow" do
      ProcessFlow.stub(:find).with("37") { mock_process_flow }
      mock_process_flow.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the process_flows list" do
      ProcessFlow.stub(:find) { mock_process_flow }
      delete :destroy, :id => "1"
      response.should redirect_to(process_flows_url)
    end
  end

end
